// issue with testing library + React 18: https://github.com/testing-library/react-testing-library/issues/1216
/* eslint-disable testing-library/no-unnecessary-act */

import { render, screen, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ChatHeader } from "../../src/components";
import { mockChatHooks, spyOnActions } from "../__utils__/mocks";

beforeEach(() => {
  mockChatHooks({
    mockedActions: {
      restartConversation: jest.fn(() => Promise.resolve()),
    },
  });
});

it("calls restartConversation when restart button is clicked", async () => {
  render(<ChatHeader title="Clippy's Chatbot" showRestartButton={true} />);

  const restartButton = screen.getByLabelText("Restart Conversation");
  await act(() => userEvent.click(restartButton));

  const actions = spyOnActions();
  expect(actions.restartConversation).toHaveBeenCalledTimes(1);
});

it("does not display restart button by default", () => {
  render(<ChatHeader title="Clippy's Chatbot" />);
  expect(screen.queryByLabelText("Restart Conversation")).toBeNull();
});

it("calls onClose when close button is clicked", async () => {
  const onClose = jest.fn();
  render(
    <ChatHeader
      title="Clippy's Chatbot"
      showCloseButton={true}
      onClose={onClose}
    />
  );

  const closeButton = screen.getByLabelText("Close Chat");
  await act(() => userEvent.click(closeButton));

  expect(onClose).toHaveBeenCalledTimes(1);
});

it("does not display close button by default", () => {
  render(<ChatHeader title="Clippy's Chatbot" />);
  expect(screen.queryByLabelText("Close Chat")).toBeNull();
});

it("displays the default AI signpost popover", async () => {
  render(<ChatHeader title="Clippy's Chatbot" />);

  const signpost = screen.getByRole("button", { name: "AI-Powered" });
  expect(screen.queryByRole("dialog")).toBeNull();

  await act(() => userEvent.click(signpost));

  expect(
    screen.getByRole("dialog", { name: "AI-Generated Content" })
  ).toBeTruthy();
  expect(
    screen.getByText(
      "This content is generated by AI from language models and previous responses. It may be incomplete or inaccurate. Please check statements for accuracy."
    )
  ).toBeTruthy();

  await act(() =>
    userEvent.click(screen.getByRole("button", { name: "Dismiss" }))
  );
  expect(screen.queryByRole("dialog")).toBeNull();
});

it("supports hiding and customizing the AI signpost", async () => {
  const { rerender } = render(
    <ChatHeader title="Clippy's Chatbot" hideAISignpost />
  );
  expect(screen.queryByRole("button", { name: "AI-Powered" })).toBeNull();

  rerender(
    <ChatHeader
      title="Clippy's Chatbot"
      aiSignpostProps={{
        icon: <span data-testid="custom-ai-signpost-icon">Custom Icon</span>,
        label: "Custom Label",
        popoverHeader: "Custom Header",
        popoverBody: "Custom Body",
      }}
    />
  );

  expect(screen.getByTestId("custom-ai-signpost-icon")).toBeTruthy();
  await act(() =>
    userEvent.click(
      screen.getByRole("button", { name: "Custom Icon Custom Label" })
    )
  );

  expect(screen.getByRole("dialog", { name: "Custom Header" })).toBeTruthy();
  expect(screen.getByText("Custom Body")).toBeTruthy();
});
