import { useChatActions } from "@yext/chat-headless-react";
import { DualSyncIcon } from "../icons/DualSync";
import { useComposedCssClasses } from "../hooks/useComposedCssClasses";
import React, { useCallback, useRef, useState } from "react";
import { twMerge } from "tailwind-merge";
import { CrossIcon } from "../icons/Cross";
import { withStylelessCssClasses } from "../utils/withStylelessCssClasses";
import { AISignpostIcon } from "../icons/AISignpostIcon";
import { useId } from "../hooks/useId";

/**
 * The CSS class interface for the {@link ChatHeader} component.
 *
 * @public
 */
export interface ChatHeaderCssClasses {
  container?: string;
  title?: string;
  restartButton?: string;
  restartButtonIcon?: string;
  closeButton?: string;
  closeButtonIcon?: string;
}

const builtInCssClasses: Readonly<ChatHeaderCssClasses> =
  withStylelessCssClasses("Header", {
    container:
      "w-full pl-4 pr-3 py-3 flex justify-between bg-gradient-to-tr from-blue-600 to-blue-800",
    title: "text-white text-xl font-medium truncate pr-1",
    restartButton: "w-8 h-8 ml-auto shrink-0 flex justify-center items-center",
    restartButtonIcon: "text-white stroke-[0.2] w-[26px] h-[26px]",
    closeButton:
      "w-8 h-8 hover:scale-110 shrink-0 flex justify-center items-center",
    closeButtonIcon: "text-white w-[26px] h-[26px]",
  });

const aiSignpostDefaults = {
  label: "AI-Powered",
  popoverHeader: "AI-Generated Content",
  popoverBody:
    "This content is generated by AI from language models and previous responses. It may be" +
      " incomplete or inaccurate. Please check statements for accuracy.",
};

/**
 * The props for the {@link ChatHeader} component.
 *
 * @public
 */
export interface ChatHeaderProps {
  /**
   * The headers's title text, essentially how the chat window identifies itself to the user.
   */
  title: string;
  /**
   * Displays a restart button which allows the user to restart the conversation.
   * Defaults to false.
   */
  showRestartButton?: boolean;
  /**
   * Displays a close button which will invoke {@link ChatHeaderProps.onClose} on click.
   * Default to false.
   */
  showCloseButton?: boolean;
  /** A function which is called when the close button is clicked.  */
  onClose?: () => void;
  /**  Custom icon for for restart button. */
  restartButtonIcon?: JSX.Element;
  /**  Custom icon for for close button. */
  closeButtonIcon?: JSX.Element;
  /** Whether to hide the AI signpost. Defaults to false. */
  hideAISignpost?: boolean;
  /** The props to pass to the built-in AI signpost component. */
  aiSignpostProps?: AISignpostProps;
  /**  CSS classes for customizing the component styling. */
  customCssClasses?: ChatHeaderCssClasses;
}

/**
 * Props for the built-in AI signpost component.
 *
 * @public
 */
export interface AISignpostProps {
  /** Icon displayed before the signpost label. Defaults to the SDK's AI signpost icon. */
  icon?: React.JSX.Element;
  /** Label displayed in the signpost button. Defaults to "AI-Powered". */
  label?: string;
  /** Header displayed in the signpost popover. Defaults to "AI-Generated Content". */
  popoverHeader?: string;
  /** Body displayed in the signpost popover. */
  popoverBody?: string;
}

/**
 * A component that renders the header of a chat bot panel,
 * including the title and a button to reset the conversation.
 *
 * @public
 *
 * @param props - {@link ChatHeaderProps}
 */
export function ChatHeader({
  title,
  showRestartButton,
  restartButtonIcon,
  showCloseButton,
  closeButtonIcon,
  hideAISignpost = false,
  aiSignpostProps,
  onClose,
  customCssClasses,
}: ChatHeaderProps) {
  const chat = useChatActions();

  const cssClasses = useComposedCssClasses(builtInCssClasses, customCssClasses);

  const [isSpinning, setIsSpinning] = useState(false);
  const restartButtonCssClasses = twMerge(
    cssClasses.restartButton,
    isSpinning ? "animate-[spin_0.3s_linear]" : "hover:scale-110"
  );

  const clearTimerRef = useRef<ReturnType<typeof setTimeout>>();
  const onRestart = useCallback(async () => {
    clearTimeout(clearTimerRef.current);
    setIsSpinning(true);
    clearTimerRef.current = setTimeout(() => {
      setIsSpinning(false);
    }, 1000);
    chat.restartConversation();
  }, [chat]);

  return (
    <div className={cssClasses.container}>
      <div className="relative flex min-w-0 items-center gap-2 pr-1">
        <h1 className={twMerge("min-w-0", cssClasses.title)}>{title}</h1>
        {!hideAISignpost && <AISignpost {...aiSignpostProps} />}
      </div>
      {showRestartButton && (
        <button
          aria-label="Restart Conversation"
          onClick={onRestart}
          className={restartButtonCssClasses}
        >
          {restartButtonIcon ?? (
            <DualSyncIcon className={cssClasses.restartButtonIcon} />
          )}
        </button>
      )}
      {showCloseButton && (
        <button
          aria-label="Close Chat"
          onClick={onClose}
          className={cssClasses.closeButton}
        >
          {closeButtonIcon ?? (
            <CrossIcon className={cssClasses.closeButtonIcon} />
          )}
        </button>
      )}
    </div>
  );
}

function AISignpost({
  icon,
  label,
  popoverHeader,
  popoverBody,
}: AISignpostProps): React.JSX.Element {
  const [isOpen, setIsOpen] = useState(false);
  const popoverId = useId("ai-signpost-popover");
  const popoverHeaderId = useId("ai-signpost-popover-header");
  const popoverDescriptionId = useId("ai-signpost-popover-description");
  const handleSignpostClick = useCallback(() => {
    setIsOpen((current) => !current);
  }, []);
  const onSignpostClose = useCallback(() => {
    setIsOpen(false);
  }, []);

  return (
    <div className="relative shrink-0 text-sm text-blue-800">
      <button
        type="button"
        aria-expanded={isOpen}
        aria-controls={popoverId}
        className="inline-flex items-center gap-1.5 rounded-lg border border-blue-100 bg-white px-2 py-1 text-xs font-medium text-blue-800 shadow-sm transition-colors hover:bg-blue-50"
        onClick={handleSignpostClick}
      >
        {icon ?? <AISignpostIcon className="h-4 w-4" />}
        <span>{label ?? aiSignpostDefaults.label}</span>
      </button>
      {isOpen && (
        <div
          id={popoverId}
          role="dialog"
          aria-labelledby={popoverHeaderId}
          aria-describedby={popoverDescriptionId}
          className="absolute left-0 top-full z-10 mt-2 w-80 max-w-[calc(100vw-2rem)] rounded-lg border border-gray-200 bg-white text-gray-700 shadow-lg"
        >
          <div className="flex flex-col gap-3 px-4 py-3">
            <div className="flex items-center justify-between gap-3">
              <div
                id={popoverHeaderId}
                className="text-sm font-semibold text-gray-900"
              >
                {popoverHeader ?? aiSignpostDefaults.popoverHeader}
              </div>
              <button
                type="button"
                className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-gray-500 hover:bg-gray-100 hover:text-gray-700"
                aria-label="Dismiss"
                onClick={onSignpostClose}
              >
                <CrossIcon className="h-3 w-3" />
              </button>
            </div>
            <div id={popoverDescriptionId} className="text-sm text-gray-700">
              {popoverBody ?? aiSignpostDefaults.popoverBody}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
